services:
  # --- User Microservice ---
  users-microservice:
    image: luciajcm/user-microservice
    container_name: users-microservice
    restart: always
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: mysql+pymysql://usersuser:userspass@${MYSQL_HOST}:3307/usersdb
      JWT_SECRET: clave-secreta-usuarios
    networks:
      - cinema-net

  # --- Theaters Microservice ---
  theaters-microservice:
    image: joemir123/theaters-api
    container_name: theaters-microservice
    restart: always
    ports:
      - "8001:8001"
    environment:
      DB_PATH: "/mnt/theaters/theaters.db"
      INIT_SCHEMA: "1"
    volumes:
      - /mnt/theaters:/mnt/theaters:rw
    networks:
      - cinema-net

  # --- Booking Microservice ---
  booking-microservice:
    image: lazheart/booking-microservice:1.0
    container_name: booking-microservice
    restart: always
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: mongodb://${MONGO_HOST}:27017/bookingdb
    networks:
      - cinema-net

  # --- Movie Microservice ---
  movie-microservice:
    image: lucianayc/movie-microservice
    container_name: movie-microservice
    restart: always
    ports:
      - "8080:8080"
    environment:
      DB_HOST: ${POSTGRES_HOST}
      DB_PORT_POSTGRES: 15432
      DB_NAME: moviesdb
      DB_USER: postgres
      DB_PASSWORD: postgres
    networks:
      - cinema-net

  # --- Nginx Reverse Proxy ---
  nginx:
    image: nginx:latest
    container_name: api-gateway
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - users-microservice
      - theaters-microservice
      - booking-microservice
      - movie-microservice
    networks:
      - cinema-net

networks:
  cinema-net:
    driver: bridge