version: "3.8"

services:
  # --- User Microservice ---
  user-microservice:
    image: lazheart/user-microservice:1.0
    container_name: user-microservice
    restart: always
    ports:
      - "5000:5000"
    environment:
      - MONGO_URL=mongodb://${MONGO_HOST}:27017/usuarios

  # --- Theaters Microservice ---
  theaters-microservice:
    image: lazheart/theaters-microservice:1.0
    container_name: theaters-microservice
    restart: always
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=sqlite:///./data/theaters.db
    volumes:
      - ./data:/app/data

  # --- Booking Microservice ---
  booking-microservice:
    image: lazheart/booking-microservice:1.0
    container_name: booking-microservice
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}

  # --- Movie Microservice ---
  movie-microservice:
    image: lazheart/movie-microservice:1.0
    container_name: movie-microservice
    restart: always
    ports:
      - "8080:8080"
