  # --- User Microservice ---
  user-microservice:
    image: lazheart/user-microservice:1.0
    container_name: user-microservice
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - MONGO_URL=mongodb://${MONGO_HOST}:27017/usuarios

  # --- Theaters Microservice ---
  theaters-microservice:
    image: lazheart/theaters-microservice:1.0
    container_name: theaters-microservice
    restart: always
    ports:
      - "8001:8001"
    volumes:
      - ./data:/app/data
    environment:
      - DATABASE_URL=sqlite:///./data/theaters.db

  # --- Booking Microservice ---
  booking-microservice:
    image: lazheart/booking-microservice:1.0
    container_name: booking-microservice
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}

  # --- Movie Microservice ---
  movie-microservice:
    image: lazheart/movie-microservice:1.0
    container_name: movie-microservice
    restart: always
    ports:
      - "8080:8080"

  # --- Nginx Reverse Proxy ---
  nginx:
    image: nginx:latest
    container_name: api-gateway
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - user-microservice
      - theaters-microservice
      - booking-microservice
      - movie-microservice
